# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: c1e6832e53dcad5f5d153a8df1793d04df828d796eb94a9dc98f537f193784fa6c0366b8ee7c354bce862a45d47b3155e6ce9a30196ff1f01fa4b5c2f6b498e8

test:
  secret_key_base: bb93f676de59766f422848ddd2283c7c7366771f0fdb98122290a0c1ea38c7397a22a569dbdb3f56e7d5174123d125a29ad65d9e6ab087333f08dd2ace06641d

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
